language: php

sudo: false

php:
  - 7.0
  - 7.1

before_script:
  - composer update
  - vendor/bin/ion info

script:
  - vendor/bin/ion vendor/bin/phpunit tests/cases

after_script:
  - php vendor/bin/coveralls